title: David Gurr
email: info@DavidGurr.com
description: "David Gurr is a graphic designer and visual strategist located in South Florida specializing in brand identity, packaging, and print design."
#baseurl: "/David-Gurr"
url: "https://davidgurr.com"

markdown: kramdown
permalink: pretty
plugins:
  - jekyll-feed

sass:
  sass_dir: _sass

collections:
  projects:
    output: true
